default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type: annotation

sso:
    resource: "@AppBundle/Controller/EveSSOController.php"
    type: annotation

admin:
    resource: "@AppBundle/Controller/Admin"
    prefix: /admin
    type: annotation

api:
    resource: "@AppBundle/Controller/Api"
    prefix: /api
    type: annotation

api.character:
    resource: "@AppBundle/Controller/Api/Character"
    prefix: /api/character
    type: annotation

api.corporation:
    resource: "@AppBundle/Controller/Api/Corporation"
    prefix: /api/corporation
    type: annotation

api.eve:
    resource: "@AppBundle/Controller/Api/Eve"
    prefix: /api/eve
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"