# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

  access_decision_manager:
      strategy: unanimous
  encoders:
      FOS\UserBundle\Model\UserInterface: bcrypt

  role_hierarchy:
      ROLE_CORP_MEMBER: ROLE_USER
      ROLE_DIRECTOR: ROLE_CORP_MEMBER
      ROLE_CEO: ROLE_DIRECTOR
      ROLE_ALLIANCE_LEADER: ROLE_CEO
      ROLE_ADMIN: ROLE_ALLIANCE_LEADER
      ROLE_SUPER_ADMIN: ROLE_ADMIN


  # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
      fos_userbundle:
        id: fos_user.user_provider.username

  firewalls:
      # disables authentication for assets and the profiler, adapt it according to your needs
      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false

      main:
          pattern: ^/
          form_login:
            provider: fos_userbundle
            csrf_provider: security.csrf.token_manager
            default_target_path: /admin/dashboard
          logout: true
          anonymous: true

      api_login:
          patter: ^/api/login
          stateless: true
          anonymous: true
          form_login:
              check_path:   /api/login_check
              success_handler: ''
              failure_handler: ''
              require_previous_session: false

      api:
          pattern: ^/api
          stateless: true

  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, role: ROLE_CORP_MEMBER }
    - { path: ^/api, role: ROLE_CORP_MEMBER }
