---
- name: Staging DO Configuration for EAU
  hosts: eve_platform
  remote_user: deploy
  roles:
    - php
    - servergrove.symfony2
    - post-install
  vars:
    server_user: deploy
    symfony2_project_root: /srv/eau
    symfony2_project_name: eau
    symfony2_project_composer_path: /srv/eau/shared
    symfony2_project_repo: git@github.com:orloc/evetool.git
    symfony2_project_branch: "staging"
    symfony2_project_php_path: php
    symfony2_project_env: dev
    symfony2_project_console_opts: '--no-debug'
    symfony2_project_composer_opts: '--no-dev --optimize-autoloader --no-interaction'
    symfony2_project_keep_releases: 3
    symfony2_project_clean_versioning: true
